name: Release AddOn

on:
  push:
    branches:
      - main
env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: BigWigsMods/packager@v2